blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('new_post/', views.create_post, name='create_post'),
    path('edit_post/<int:post_id>', views.edit_post, name='edit_post'),
    path('delete_post/<int:post_id>', views.delete_post, name='delete_post'),
    path('<slug:cat>/', views.post_list, name='post_list'),
    path('', views.post_list, name='post_list'),
]

prowork/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', include('index.urls', namespace='index')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class Area(models.Model):
    STATUS_CHOICES = (
        ('active', 'Active'),
        ('inactive', 'Inactive'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,unique_for_date='publish')
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,choices=STATUS_CHOICES,default='inactive')

    class Meta:
        ordering = ('title',)
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_list', args=[self.slug])

class Category(models.Model):
    STATUS_CHOICES = (
        ('active', 'Active'),
        ('inactive', 'Inactive'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,unique_for_date='publish')
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,choices=STATUS_CHOICES,default='inactive')

    class Meta:
        ordering = ('title',)
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_list', args=[self.slug])
        
class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,unique_for_date='publish')
    author = models.ForeignKey(User,on_delete=models.CASCADE,related_name='blog_posts')
    photo = models.ImageField(upload_to='blog/%Y/%m/%d/', blank=True)
    body = models.TextField()
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    area = models.ForeignKey(Area,on_delete=models.CASCADE)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,choices=STATUS_CHOICES,default='draft')

    class Meta:
        ordering = ('-publish',)
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,
                                self.publish.month, self.publish.day, self.slug])

blog/forms.py
from django import forms
from .models import Post
from django.contrib.auth.models import User

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'photo', 'body', 'category', 'area', 'status')

class PostEditForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'photo', 'body', 'category', 'area', 'status')

blog/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Post, Category, Area
from .forms import PostForm, PostEditForm
from django.utils import timezone
import datetime
from django.contrib import messages
from django.utils.text import slugify

def post_list(request, cat=None):

    cat_id = Category.objects.filter(status='active', slug=cat).first()
    area_id = Area.objects.filter(status='active', slug=cat).first()
    if cat_id:
        object_list = Post.objects.filter(status='published', category=cat_id.id).all()
    elif area_id:
        object_list = Post.objects.filter(status='published', area=area_id.id).all()
    else:
        object_list = Post.objects.filter(status='published').all()

    cats = Category.objects.filter(status='active').all()
    areas = Area.objects.filter(status='active').all()

    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    
    if request.user.is_authenticated:
        my_posts = Post.objects.filter(author=request.user.id).all()
    
    return render(request,'blog/post/list.html', locals() )

def post_detail(request, year, month, day, post):

    cats = Category.objects.filter(status='active').all()
    areas = Area.objects.filter(status='active').all()
    if request.user.is_authenticated:
        my_posts = Post.objects.filter(author=request.user.id).all()
    post = get_object_or_404(Post, slug = post, status = 'published',
                publish__year = year, publish__month = month, publish__day = day)

    return render(request, 'blog/post/detail.html',	locals() )


@login_required
def create_post(request):
    blocks = 1
    if request.method == 'POST':
        post_form = PostForm(data = request.POST, files = request.FILES)
        blocks = 2
        if post_form.is_valid():
            new_post = post_form.save(commit=False)
            new_post.slug = slugify(new_post.title)
            new_post.author = request.user
            new_post.save()
            blocks = 3
            return redirect(new_post.get_absolute_url())
    else:
        post_form = PostForm()
    
    cats = Category.objects.filter(status='active').all()
    areas = Area.objects.filter(status='active').all()
    my_posts = Post.objects.filter(author=request.user.id).all()
    
    return render(request, 'blog/post/create_post.html', locals())

@login_required
def edit_post(request, post_id):
    postt = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        post_form = PostEditForm(data=request.POST, files = request.FILES)
        if post_form.is_valid():
            new_post = post_form.save(commit=False)
            new_post.slug = slugify(new_post.title)
            new_post.author = request.user
            new_post.updated = datetime.datetime.now()
            new_post.save()
            messages.success(request, 'O\'zgartirish muvaffaqiyatli saqlandi')
            return redirect(new_post.get_absolute_url())
        else:
            messages.error(request, 'O\'zgartirishda xatolik sodir bo\'ldi')
    else:
        post_form = PostEditForm(instance=postt)

    cats = Category.objects.filter(status='active').all()
    areas = Area.objects.filter(status='active').all()
    my_posts = Post.objects.filter(author=request.user.id).all()

    return render(request,'blog/post/edit_post.html', locals())


@login_required
def delete_post(request, post_id):
    
    Post.objects.filter(pk=post_id).delete()

    return redirect('index:index')

templates/blog/post/create_post.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %} My Blog {% endblock %}


{% block mypost %}

  {% if request.user.is_authenticated %}
    <li>
      <a href="#">
        <i class="metismenu-icon pe-7s-plugin"></i>
        Mening postlarim
        <i class="metismenu-state-icon pe-7s-angle-down caret-left"></i>
      </a>
      <ul>
        {% for my_post in my_posts %}
          <li>
            <a href="{{ my_post.get_absolute_url }}">
              <i class="metismenu-icon"></i> {{ my_post.title }}
            </a>
          </li>
          {% empty %}
          <li>Sizda post mavjud emas</li>
        {% endfor %}
        <li>
          <a href="#" class="btn btn-primary" style="color: black;">
            <i class="metismenu-icon"></i> Post yaratish
          </a>
        </li>
      </ul>
    </li>
  {% endif %}

{% endblock %}

{% block content %}
  <div class="col-md-12">
    <div class="main-card mb-3 card">
      <div class="card-body">
        <form action method="post" enctype='multipart/form-data'>
          {% csrf_token %}
          <div class="card-body">
            
            <div class="position-relative form-group">
              <label for="id_title">Title</label>
              <input type="text" name="title" maxlength="250" required id="id_title" class="form-control">
            </div>
                
            <div class="position-relative form-group">
              <label for="id_body" class="col-form-label">Body</label>
              <div>
                <textarea name="body" rows="10" id="id_body" required class="form-control"></textarea>
              </div>
            </div>

            <div class="position-relative form-group">
              <label for="id_photo" class="col-form-label">Photo</label>
              <div>
                <input name="photo" id="id_photo" accept="image/*" type="file" class="form-control-file" required>
                <small class="form-text text-muted"></small>
              </div>
            </div>

            <div class="row">
              <div class="col-md-4 position-relative form-group">
                <label for="id_category">Categoriya</label>
                <select name="category" required id="id_category" class="form-control">
                  <option value selected disabled> ------- </option>
                  {% for cat in cats %}
                    <option value="{{ cat.id}}" > {{ cat.title }} </option>
                  {% endfor %}
                </select>
              </div>
              <div class="col-md-4 position-relative form-group">
                <label for="id_area">Area</label>
                <select name="area" required id="id_area" class="form-control">
                  <option value selected disabled> ------- </option>
                  {% for area in areas %}
                    <option value="{{area.id}}"> {{ area.title }} </option>
                  {% endfor %}
                </select>
              </div>
              <div class="col-md-4 position-relative form-group">
                <label for="id_status">Publish</label>
                <select name="status" id="id_status" class="form-control">
                  <option value="draft" selected> Draft </option>
                  <option value="published"> Published </option>
                </select>
              </div>
            </div>

          </div>                
          
          <div class="divider"></div>
          <div class="clearfix text-center">
            <button type="submit" class="btn-shadow btn-wide btn-pill btn-hover-shine btn btn-primary">Saqlash</button>
          </div>
        </form>
      </div>
    </div>
  </div>

{% endblock %}

templates/blog/post/delete_post.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %} My Blog {% endblock %}


{% block mypost %}

  {% if request.user.is_authenticated %}
    <li>
      <a href="#">
        <i class="metismenu-icon pe-7s-plugin"></i>
        Mening postlarim
        <i class="metismenu-state-icon pe-7s-angle-down caret-left"></i>
      </a>
      <ul>
        {% for my_post in my_posts %}
          <li>
            <a href="{{ my_post.get_absolute_url }}">
              <i class="metismenu-icon"></i> {{ my_post.title }}
            </a>
          </li>
          {% empty %}
          <li>Sizda post mavjud emas</li>
        {% endfor %}
        <li>
          <a href="#" class="btn btn-primary" style="color: black;">
            <i class="metismenu-icon"></i> Post yaratish
          </a>
        </li>
      </ul>
    </li>
  {% endif %}

{% endblock %}

{% block content %}
  <div class="col-md-12">
    <div class="main-card mb-3 card">
      <div class="card-body">
        <div class="no-results">
          <div class="swal2-icon swal2-success swal2-animate-success-icon">
            <div class="swal2-success-circular-line-left" style="background-color: rgb(255, 255, 255);"></div>
            <span class="swal2-success-line-tip"></span>
            <span class="swal2-success-line-long"></span>
            <div class="swal2-success-ring"></div>
            <div class="swal2-success-fix" style="background-color: rgb(255, 255, 255);"></div>
            <div class="swal2-success-circular-line-right" style="background-color: rgb(255, 255, 255);"></div>
          </div>
          <div class="results-subtitle mt-4"> Danger!!!</div>
          <div class="results-title"> Siz haqiqatdan ham ushbu postni o'chirmoqchimisiz? </div>
          <div class="mt-3 mb-3"></div>
          <div class="text-center">
            <a href="{% url 'blog:create_post' %}" class="btn-shadow btn-wide btn btn-success btn-lg">Postga qaytish</a>
            <a href="{% url 'blog:del_post' posts.id post.id %}" class="btn-shadow btn-wide btn btn-success btn-lg"> O'chirish </a>
          </div>
        </div>
      </div>
      <div class="divider"></div>
    </div>
  </div>

{% endblock %}

templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block mypost %}
  
  {% if request.user.is_authenticated %}
    <li>
      <a href="#">
        <i class="metismenu-icon pe-7s-plugin"></i>
        Mening postlarim
        <i class="metismenu-state-icon pe-7s-angle-down caret-left"></i>
      </a>
      <ul>
        {% for my_post in my_posts %}
          <li>
            <a href="{{ my_post.get_absolute_url }}">
              <i class="metismenu-icon"></i> {{ my_post.title }}
            </a>
          </li>
          {% empty %}
          <li>Sizda post mavjud emas</li>
        {% endfor %}
        <li>
          <a href="{% url 'blog:create_post' %}" class="btn btn-primary" style="color: #000000;">
            <i class="metismenu-icon"></i> Post yaratish
          </a>
        </li>
      </ul>
    </li>
  {% endif %}

{% endblock %}


{% block content %}
	         <div class="modal fade bd-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" style="display: none;" aria-modal="true">
              <div class="modal-dialog modal-sm">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Warning</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">×</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <p>Siz haqiqatdan ham ushbu postni o'chirishni istaysizmi? O'chirilgan ma'lumotlar qayta tiklanmaydi!!!</p>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <a href="{% url 'blog:delete_post' post.id %}" class="btn btn-danger">O'chirish</a>
                  </div>
                </div>
              </div>
            </div>

	<div class="col-md-12">
    	<div class="main-card mb-3 card">
      		<div class="card-body">
        		<h5 class="card-title"> {{ post.title }} </h5>
      		</div>
      		<img width="100%" src="{{ post.photo.url }} " alt="Card image cap">
      		<div class="card-body">
      			<div>
		        	<div class="date" style="float:left;">
		            	{{ post.publish | date:"d.m.Y" }}
		          	</div>
		          	<div class="author" style="float:right;">
		            	{{ post.author }}
		          	</div>
		        </div>
		        <div class="mt-4 text-justify">
		        	{{ post.body }}
		        </div>
		        <p>
		        	
  				{% if user == post.author %}
            <div class="col-md-12 text-center">
              <button type="button" data-toggle="popover-custom-content" rel="popover-focus" popover-id="0" class="mr-2 mb-2 btn btn-danger" data-original-title="" title="">O'chirish</button>

        			<a href="{% url 'blog:edit_post' post.id %}"class="btn btn-info ml-5">Yangilash</a>


              <div id="popover-content-0" class="d-none">
                <div class="dropdown-menu-header">
                  <div class="dropdown-menu-header-inner bg-primary">
                    <div class="menu-header-image opacity-5" style="background-image: url('assets/images/dropdown-header/abstract2.jpg');"></div>
                    <div class="menu-header-content">
                      <h5 class="menu-header-title">WARNING!!!</h5>
                    </div>
                  </div>
                </div>
                <ul class="nav flex-column">
                  <li class="nav-item-header nav-item">Siz haqiqatdan ham</li>
                  <li class="nav-item-header nav-item">ushbu postni o'chirishni istaysizmi?</li>
                  <li class="nav-item-header nav-item">O'chirilgan ma'lumotlar </li>
                  <li class="nav-item-header nav-item">qayta tiklanmaydi!!! </li>

                  <li class="nav-item-divider nav-item"></li>
                  <li class="nav-item-btn nav-item text-center">
                    <a href="{% url 'blog:delete_post' post.id %}" class="btn-wide btn-shadow btn btn-danger btn-sm">O'chirish</a>
                  </li>
                </ul>
              </div>
            </div>

        		{% endif %}
		        </p>

      		</div>
    	</div>
  	</div>
    
{% endblock %}

templates/blog/post/edit_post.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %} My Blog {% endblock %}


{% block mypost %}

  {% if request.user.is_authenticated %}
    <li>
      <a href="#">
        <i class="metismenu-icon pe-7s-plugin"></i>
        Mening postlarim
        <i class="metismenu-state-icon pe-7s-angle-down caret-left"></i>
      </a>
      <ul>
        {% for my_post in my_posts %}
          <li>
            <a href="{{ my_post.get_absolute_url }}">
              <i class="metismenu-icon"></i> {{ my_post.title }}
            </a>
          </li>
          {% empty %}
          <li>Sizda post mavjud emas</li>
        {% endfor %}
        <li>
          <a href="#" class="btn btn-primary" style="color: black;">
            <i class="metismenu-icon"></i> Post yaratish
          </a>
        </li>
      </ul>
    </li>
  {% endif %}

{% endblock %}

{% block content %}
  <div class="col-md-12">
    <div class="main-card mb-3 card">
      <div class="card-body">
        <form action method="post" enctype='multipart/form-data'>
          {% csrf_token %}
          <div class="card-body">
            {{ post_form.non_field_errors }}
            <div class="position-relative form-group">
              {{ post_form.title.errors }}
              <label for="{{ post_form.title.id_for_label }}">Title</label>
              <input type="text" name="title" value="{{ post_form.title.value }}" maxlength="250" required id="{{ post_form.title.id_for_input }}" class="form-control">
            </div>
                
            <div class="position-relative form-group">
              {{ post_form.body.errors }}
              <label for="{{ post_form.body.id_for_label }}" class="col-form-label">Body</label>
              <div>
                <textarea name="body" rows="10" id="{{ post_form.body.id_for_input }}" required class="form-control">{{ post_form.body.value }}</textarea>
              </div>
            </div>

            <div class="position-relative form-group">
              {{ post_form.photo.errors }}
              <label for="{{ post_form.photo.id_for_label }}" class="col-form-label">Photo</label>
              <div>
                {{ post_form.photo }}
              </div>
            </div>

            <div class="row">
              <div class="col-md-4 position-relative form-group">
                {{ post_form.category.errors }}
                <label for="{{ post_form.category.id_for_label }}">Categoriya</label>
                <select name="category" required id="{{ post_form.category.id_for_input }}" class="form-control">
                  <option value disabled> ------- </option>
                  {% for cat in cats %}
                    
                    <option value="{{cat.id}}" {% if cat.id == post_form.category.value %} selected  {% endif %}> {{ cat.title }} </option>
                    
                  {% endfor %}
                </select>
              </div>
              <div class="col-md-4 position-relative form-group">
                {{ post_form.category.errors }}
                <label for="{{ post_form.area.id_for_label }}">Area</label>
                <select name="area" required id="{{ post_form.area.id_for_input }}" class="form-control">
                  <option value disabled> ------- </option>
                  {% for area in areas %}
                    <option value="{{area.id}}" {% if area.id == post_form.area.value %} selected  {% endif %}> {{ area.title }} </option>
                  {% endfor %}
                </select>
              </div>
              <div class="col-md-4 position-relative form-group">
                {{ post_form.status.errors }}
                <label for="{{ post_form.status.id_for_label }}">Publish</label>
                <select name="status" id="{{ post_form.status.id_for_input }}" class="form-control">
                  {% if post_form.status.value == 'draft' %}
                    <option value="draft" selected> Draft </option>
                    <option value="published"> Published </option>
                  {% else %}
                    <option value="draft"> Draft </option>
                    <option value="published" selected> Published </option>
                  {% endif %}
                </select>
              </div>
            </div>

          </div> 
          <div class="divider"></div>
          <div class="clearfix text-center">
            <button type="submit" class="btn-shadow btn-wide btn-pill btn-hover-shine btn btn-primary">Saqlash</button>
          </div>
        </form>
      </div>
    </div>
  </div>

{% endblock %}

templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %} My Blog {% endblock %}


{% block mypost %}
  
  {% if request.user.is_authenticated %}
    <li>
      <a href="#">
        <i class="metismenu-icon pe-7s-plugin"></i>
        Mening postlarim
        <i class="metismenu-state-icon pe-7s-angle-down caret-left"></i>
      </a>
      <ul>
        {% for my_post in my_posts %}
          <li>
            <a href="{{ my_post.get_absolute_url }}">
              <i class="metismenu-icon"></i> {{ my_post.title }}
            </a>
          </li>
          {% empty %}
          <li>Sizda post mavjud emas</li>
        {% endfor %}
        <li>
          <a href="{% url 'blog:create_post' %}" class="btn btn-primary" style="color: black;">
            <i class="metismenu-icon"></i> Post yaratish
          </a>
        </li>
      </ul>
    </li>
  {% endif %}

{% endblock %}

{% block content %}
  
  {% for post in posts %}
    <div class="col-md-4">
      <div class="main-card mb-3 card">
        <img width="100%" src="{{ post.photo.url }} " alt="Card image cap" class="card-img-top">
        <div class="mt-3 ml-3 mr-3">
          <div class="date" style="float:left;">
            {{ post.publish | date:"d.m.Y" }}
          </div>
          <div class="author" style="float:right;">
            {{ post.author }}
          </div>
        </div>
        <div class="card-body">
          <h5 class="card-title">
            <a href="{{ post.get_absolute_url }}"> {{ post.title }} </a>
          </h5>
          {{ post.body|truncatewords_html:30 }}
        </div>
        <a href="{{ post.get_absolute_url }}" class="btn btn-info">Batafsil...</a>
      </div>
    </div>
  {% endfor %}
  <div class="col-md-12 text-center">
    {% include "../pagination.html" with page=posts %}
  </div>

{% endblock %}